POST http://localhost:5000/notes
Content-Type: application/json

{
    "username": "123",
    "password": "123",
    "confirm_password": "123"
}

###
POST http://localhost:5000/notes
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}

###
GET http://localhost:5000/token
